export const TODO_LIST = [
  { label: 'hoge', isFinished: false },
  { label: 'fuga', isFinished: true },
  { label: 'piyo', isFinished: true },
  { label: 'hogehoge', isFinished: false },
  { label: 'fugafuga', isFinished: true },
  { label: 'piyopiyo', isFinished: true },
  { label: 'foo', isFinished: false },
  { label: 'bar', isFinished: false },
  { label: 'baz', isFinished: true },
  { label: 'qux', isFinished: true },
  { label: 'quux', isFinished: true },
  { label: 'corge', isFinished: true },
  { label: 'grault', isFinished: true },
]
